[project]
name = 'Digital-Museum-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donation-tracker]
path = 'contracts/donation-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.educational-content]
path = 'contracts/educational-content.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
